import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import matter from "gray-matter";

// Scans roots/ and vault/agents/ on startup, validates manifests, resolves
// dependencies, and regenerates vault/agents/registry.md so the core session
// always has an up-to-date catalog of what's installed.
//
// Roots: /app/roots/<name>/manifest.yaml (+ cli.js or similar)
// Agents: /app/vault/agents/<name>/SKILL.md (with extended frontmatter)

const ROOTS_DIR = process.env.ROOTS_DIR || "/app/roots";
const AGENTS_DIR = process.env.AGENTS_DIR || "/app/vault/agents";
const REGISTRY_MD = path.join(AGENTS_DIR, "registry.md");

const roots = new Map();  // name → { manifest, dir }
const agents = new Map(); // name → { name, description, requires, tools, skillPath, dir }

function loadRoots() {
  roots.clear();
  if (!fs.existsSync(ROOTS_DIR)) {
    console.log(`Registry: no roots directory at ${ROOTS_DIR}; skipping.`);
    return;
  }
  for (const entry of fs.readdirSync(ROOTS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name.startsWith(".") || entry.name.startsWith("_")) continue;
    const manifestPath = path.join(ROOTS_DIR, entry.name, "manifest.yaml");
    if (!fs.existsSync(manifestPath)) {
      console.log(`Registry: root '${entry.name}' has no manifest.yaml; skipping.`);
      continue;
    }
    try {
      const raw = fs.readFileSync(manifestPath, "utf8");
      const manifest = yaml.load(raw) || {};
      if (!manifest.name) {
        console.warn(`Registry: root '${entry.name}' manifest missing 'name'; using folder name.`);
        manifest.name = entry.name;
      }
      roots.set(manifest.name, { manifest, dir: path.join(ROOTS_DIR, entry.name) });
    } catch (err) {
      console.error(`Registry: failed to parse root '${entry.name}' manifest — ${err.message}`);
    }
  }
  console.log(`Registry: loaded ${roots.size} root(s): ${[...roots.keys()].join(", ") || "(none)"}`);
}

function loadAgents() {
  agents.clear();
  if (!fs.existsSync(AGENTS_DIR)) {
    console.log(`Registry: no agents directory at ${AGENTS_DIR}; skipping.`);
    return;
  }
  for (const entry of fs.readdirSync(AGENTS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name.startsWith(".") || entry.name.startsWith("_")) continue;
    const skillPath = path.join(AGENTS_DIR, entry.name, "SKILL.md");
    if (!fs.existsSync(skillPath)) {
      console.log(`Registry: agent '${entry.name}' has no SKILL.md; skipping.`);
      continue;
    }
    try {
      const parsed = matter.read(skillPath);
      const fm = parsed.data || {};
      const name = fm.name || entry.name;
      const description = fm.description || fm.title || name;
      const requires = Array.isArray(fm.requires) ? fm.requires : [];
      const tools = Array.isArray(fm.tools) ? fm.tools : null;
      agents.set(name, {
        name,
        description,
        requires,
        tools,
        skillPath,
        dir: path.join(AGENTS_DIR, entry.name),
      });
    } catch (err) {
      console.error(`Registry: failed to parse agent '${entry.name}' SKILL.md — ${err.message}`);
    }
  }
  console.log(`Registry: loaded ${agents.size} agent(s): ${[...agents.keys()].join(", ") || "(none)"}`);
}

function validateDependencies() {
  for (const [name, agent] of agents) {
    const missing = agent.requires.filter((r) => !roots.has(r));
    if (missing.length > 0) {
      console.warn(`Registry: agent '${name}' requires missing roots: ${missing.join(", ")}. It will still be registered, but tool calls may fail until the roots are installed.`);
    }
  }
}

function regenerateRegistryMd() {
  const header = [
    "---",
    "title: Agent Registry",
    "type: system",
    "generated: true",
    "---",
    "",
    "<!-- Auto-generated by src/registry.js on core startup. Edit each agent's SKILL.md frontmatter instead of this file. -->",
    "",
  ];
  const lines = [...header];

  lines.push("## Available Agents", "");
  if (agents.size === 0) {
    lines.push("_No agents installed._", "");
  } else {
    for (const [name, agent] of agents) {
      lines.push(`### ${name}`);
      lines.push(`- **Description**: ${agent.description}`);
      if (agent.requires.length > 0) {
        lines.push(`- **Requires roots**: ${agent.requires.join(", ")}`);
      }
      lines.push(`- **Path**: ${agent.dir}`);
      lines.push("");
    }
  }

  lines.push("## Available Roots", "");
  if (roots.size === 0) {
    lines.push("_No roots installed._", "");
  } else {
    for (const [name, root] of roots) {
      lines.push(`### ${name}`);
      if (root.manifest.description) lines.push(`- **Description**: ${root.manifest.description}`);
      if (Array.isArray(root.manifest.commands) && root.manifest.commands.length > 0) {
        lines.push("- **Commands**:");
        for (const c of root.manifest.commands) {
          const usage = c.usage || c.name || "";
          const desc = c.description ? ` — ${c.description}` : "";
          lines.push(`  - \`${usage}\`${desc}`);
        }
      }
      lines.push(`- **Path**: ${root.dir}`);
      lines.push("");
    }
  }

  try {
    fs.writeFileSync(REGISTRY_MD, lines.join("\n"));
  } catch (err) {
    console.error(`Registry: failed to write ${REGISTRY_MD} — ${err.message}`);
  }
}

function init() {
  loadRoots();
  loadAgents();
  validateDependencies();
  regenerateRegistryMd();
}

function getRoots() {
  return [...roots.values()].map((r) => ({
    name: r.manifest.name,
    version: r.manifest.version,
    description: r.manifest.description,
    commands: r.manifest.commands || [],
    dir: r.dir,
  }));
}

function getAgents() {
  return [...agents.values()].map((a) => ({
    name: a.name,
    description: a.description,
    requires: a.requires,
    tools: a.tools,
    dir: a.dir,
  }));
}

export default { init, getRoots, getAgents };
