import Database from "better-sqlite3";
import matter from "gray-matter";
import { watch } from "chokidar";
import fs from "fs";
import path from "path";
import { VaultGraph } from "./graph.js";
import { slugify } from "./schema-validator.js";

// Graph-oriented vault index. SQLite is the edge store; heavy queries run in
// JS (see graph.js). Rebuild happens on a debounced file-watcher.
//
// Schema:
//   notes(id PK, path, title, type, created, updated, content)
//   aliases(note_id, alias_lc)  — one row per alias, lowercased for lookup
//   properties(note_id, key, value)  — arbitrary frontmatter
//   tags(note_id, tag)
//   links(source_id, target_id, target_text)
//     - target_id NULL = unresolved (dangling) link; target_text always set
//   centrality(note_id, degree_in, degree_out, pagerank)
//   notes_fts(note_id, title, content)  — FTS5 for text search

let db;
let vaultPath;
let watcher;
let rebuildTimer = null;
let rebuilding = false;
let onRebuiltCb = null;

const WIKILINK_RE = /\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]/g;
const STANDARD_FIELDS = new Set([
  "id", "title", "type", "aliases", "tags", "entities",
  "created", "updated", "related",
]);

// Paths that are config, not memory — don't index as notes.
function isIgnored(relPath) {
  const p = relPath.replace(/\\/g, "/");
  if (p.startsWith("startup/")) return true;
  if (p.startsWith("assets/")) return true; // binary asset storage; stubs live in core/
  if (p === "agents/_rules.md") return true;
  if (p === "agents/registry.md") return true; // auto-generated by registry.js
  if (/^agents\/[^/]+\/SKILL\.md$/.test(p)) return true;
  return false;
}

export function init(vaultDir, { rebuild = false, watch: shouldWatch = false, onRebuilt = null } = {}) {
  vaultPath = vaultDir;
  onRebuiltCb = onRebuilt;
  const dbPath = path.join(vaultPath, "index.db");
  // Never leak a handle: a second init() would otherwise leave the previous
  // Database unreferenced but open, and its native finalizer can then fire
  // against a torn-down environment (the RemoveEnvironmentCleanupHook abort).
  if (db) {
    try { db.close(); } catch { /* already closed */ }
    db = null;
  }
  db = new Database(dbPath);
  db.pragma("journal_mode = WAL");
  db.pragma("synchronous = NORMAL");

  createSchema();

  // CLI callers pass no options — they just query the existing DB maintained
  // by the server-side watcher, which keeps the cost per CLI invocation low
  // (~50ms vs. a full rescan). The server calls with { rebuild: true, watch: true }.
  if (rebuild) fullRebuild();

  if (shouldWatch) {
    watcher = watch(vaultPath, {
      ignored: /(^|[/\\])\.|index\.db|index\.db-wal|index\.db-shm/,
      persistent: true,
      ignoreInitial: true,
    });
    watcher.on("add", scheduleRebuild);
    watcher.on("change", scheduleRebuild);
    watcher.on("unlink", scheduleRebuild);
  }

  console.error(`Vault indexer initialized. Path: ${vaultPath}`);
}

function scheduleRebuild() {
  if (rebuildTimer) clearTimeout(rebuildTimer);
  rebuildTimer = setTimeout(() => {
    rebuildTimer = null;
    if (rebuilding) {
      // Another rebuild landed; reschedule
      scheduleRebuild();
      return;
    }
    try {
      fullRebuild();
    } catch (err) {
      console.error("Vault rebuild failed:", err.message);
    }
  }, 500);
}

function createSchema() {
  db.exec(`
    CREATE TABLE IF NOT EXISTS notes (
      id TEXT PRIMARY KEY,
      path TEXT NOT NULL,
      title TEXT,
      type TEXT,
      created TEXT,
      updated TEXT,
      content TEXT
    );
    CREATE INDEX IF NOT EXISTS idx_notes_path ON notes(path);
    CREATE INDEX IF NOT EXISTS idx_notes_type ON notes(type);

    CREATE TABLE IF NOT EXISTS aliases (
      note_id TEXT NOT NULL,
      alias_lc TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_aliases_alias ON aliases(alias_lc);
    CREATE INDEX IF NOT EXISTS idx_aliases_note ON aliases(note_id);

    CREATE TABLE IF NOT EXISTS properties (
      note_id TEXT NOT NULL,
      key TEXT NOT NULL,
      value TEXT
    );
    CREATE INDEX IF NOT EXISTS idx_properties_key ON properties(key);
    CREATE INDEX IF NOT EXISTS idx_properties_note ON properties(note_id);

    CREATE TABLE IF NOT EXISTS tags (
      note_id TEXT NOT NULL,
      tag TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_tags_tag ON tags(tag);
    CREATE INDEX IF NOT EXISTS idx_tags_note ON tags(note_id);

    CREATE TABLE IF NOT EXISTS links (
      source_id TEXT NOT NULL,
      target_id TEXT,
      target_text TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_links_source ON links(source_id);
    CREATE INDEX IF NOT EXISTS idx_links_target_id ON links(target_id);
    CREATE INDEX IF NOT EXISTS idx_links_target_text ON links(target_text);

    CREATE TABLE IF NOT EXISTS centrality (
      note_id TEXT PRIMARY KEY,
      degree_in INTEGER DEFAULT 0,
      degree_out INTEGER DEFAULT 0,
      pagerank REAL DEFAULT 0
    );
  `);

  const hasFts = db
    .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='notes_fts'")
    .get();
  if (!hasFts) {
    db.exec(`CREATE VIRTUAL TABLE notes_fts USING fts5(note_id, title, content, tokenize='porter')`);
  }
}

function findMarkdownFiles(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
      results.push(...findMarkdownFiles(full));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      results.push(full);
    }
  }
  return results;
}

function deriveId(fm, filePath) {
  if (fm.id && /^[a-z0-9][a-z0-9-]*$/.test(String(fm.id))) return String(fm.id);
  if (fm.title) return slugify(fm.title);
  return slugify(path.basename(filePath, ".md"));
}

function extractWikilinks(text) {
  const out = new Set();
  let m;
  WIKILINK_RE.lastIndex = 0;
  while ((m = WIKILINK_RE.exec(text)) !== null) {
    out.add(m[1].trim().toLowerCase());
  }
  return out;
}

function fullRebuild() {
  rebuilding = true;
  try {
    const files = findMarkdownFiles(vaultPath);

    // Parse pass — no DB writes yet, because link resolution needs the alias
    // table populated first.
    const parsed = [];
    for (const filePath of files) {
      const relPath = path.relative(vaultPath, filePath).replace(/\\/g, "/");
      if (isIgnored(relPath)) continue;
      try {
        const raw = fs.readFileSync(filePath, "utf8");
        const { data: fm, content } = matter(raw);
        const id = deriveId(fm, filePath);
        const title = fm.title || path.basename(filePath, ".md");
        const type = fm.type || "note";

        // Aliases: explicit frontmatter + title (lowercased) + filename stem
        const aliasSet = new Set();
        if (Array.isArray(fm.aliases)) for (const a of fm.aliases) aliasSet.add(String(a).toLowerCase());
        aliasSet.add(String(title).toLowerCase());
        aliasSet.add(path.basename(filePath, ".md").toLowerCase());
        aliasSet.add(id);

        // Tags
        const tags = Array.isArray(fm.tags) ? fm.tags.map(String) : [];

        // Properties: anything in frontmatter not in the standard set
        const properties = [];
        for (const [k, v] of Object.entries(fm)) {
          if (STANDARD_FIELDS.has(k)) continue;
          if (v === null || v === undefined) continue;
          const str = Array.isArray(v) ? JSON.stringify(v) : String(v);
          properties.push({ key: k, value: str });
        }

        // Wikilink targets: scan raw file text. Also fold frontmatter.entities
        // and frontmatter.related into link-texts so they act as implicit links.
        const linkTexts = extractWikilinks(raw);
        if (Array.isArray(fm.entities)) {
          for (const e of fm.entities) linkTexts.add(String(e).toLowerCase());
        }
        if (Array.isArray(fm.related)) {
          for (const r of fm.related) linkTexts.add(String(r).replace(/^\[\[|\]\]$/g, "").toLowerCase());
        }

        parsed.push({
          id,
          path: relPath,
          title,
          type,
          created: fm.created ? String(fm.created) : "",
          updated: fm.updated ? String(fm.updated) : "",
          content,
          aliases: [...aliasSet],
          tags,
          properties,
          linkTexts: [...linkTexts],
        });
      } catch (err) {
        console.error(`Vault: failed to parse ${filePath} — ${err.message}`);
      }
    }

    // Write pass — all in one transaction for atomicity.
    const tx = db.transaction(() => {
      db.exec("DELETE FROM notes; DELETE FROM aliases; DELETE FROM properties; DELETE FROM tags; DELETE FROM links; DELETE FROM centrality; DELETE FROM notes_fts;");

      const insertNote = db.prepare("INSERT OR REPLACE INTO notes (id, path, title, type, created, updated, content) VALUES (?,?,?,?,?,?,?)");
      const insertAlias = db.prepare("INSERT INTO aliases (note_id, alias_lc) VALUES (?, ?)");
      const insertProp = db.prepare("INSERT INTO properties (note_id, key, value) VALUES (?, ?, ?)");
      const insertTag = db.prepare("INSERT INTO tags (note_id, tag) VALUES (?, ?)");
      const insertLink = db.prepare("INSERT INTO links (source_id, target_id, target_text) VALUES (?, ?, ?)");
      const insertFts = db.prepare("INSERT INTO notes_fts (note_id, title, content) VALUES (?, ?, ?)");

      // First, insert notes + aliases + properties + tags + fts
      for (const n of parsed) {
        insertNote.run(n.id, n.path, n.title, n.type, n.created, n.updated, n.content);
        insertFts.run(n.id, n.title, n.content);
        for (const a of n.aliases) insertAlias.run(n.id, a);
        for (const p of n.properties) insertProp.run(n.id, p.key, p.value);
        for (const t of n.tags) insertTag.run(n.id, t);
      }

      // Then, resolve links via the alias table
      const resolveAlias = db.prepare("SELECT note_id FROM aliases WHERE alias_lc = ?");
      for (const n of parsed) {
        for (const text of n.linkTexts) {
          const hit = resolveAlias.get(text);
          insertLink.run(n.id, hit?.note_id || null, text);
        }
      }
    });
    tx();

    // Centrality: build graph from the links table, compute, write back
    const graph = new VaultGraph(db);
    const degrees = graph.degrees();
    const ranks = graph.pageRank({ iterations: 25, damping: 0.85 });

    const upsertCentrality = db.prepare(
      "INSERT OR REPLACE INTO centrality (note_id, degree_in, degree_out, pagerank) VALUES (?, ?, ?, ?)"
    );
    const centralityTx = db.transaction(() => {
      for (const { id } of db.prepare("SELECT id FROM notes").all()) {
        const d = degrees.get(id) || { in: 0, out: 0 };
        const r = ranks.get(id) || 0;
        upsertCentrality.run(id, d.in, d.out, r);
      }
    });
    centralityTx();

    console.error(`Indexed ${parsed.length} notes.`);
    if (onRebuiltCb) {
      try { onRebuiltCb(db); } catch (err) { console.error("onRebuilt hook failed:", err.message); }
    }
  } finally {
    rebuilding = false;
  }
}

// Close the watcher and the SQLite handle explicitly. better-sqlite3 registers
// a Node environment cleanup hook per Database; letting the process exit with a
// live handle leaves that hook to run during teardown, which is where the
// `RemoveEnvironmentCleanupHook ... (env) != nullptr` abort comes from. Closing
// deterministically removes the hook while the environment still exists.
export function close() {
  if (rebuildTimer) {
    clearTimeout(rebuildTimer);
    rebuildTimer = null;
  }
  if (watcher) {
    try { watcher.close(); } catch { /* ignore */ }
    watcher = undefined;
  }
  if (db) {
    try { db.close(); } catch { /* ignore */ }
    db = null;
  }
}

// ---------- Query helpers (used by vault-cli.js) ----------

export function resolveAlias(text) {
  const hit = db.prepare("SELECT note_id FROM aliases WHERE alias_lc = ? LIMIT 1").get(String(text).toLowerCase());
  return hit?.note_id || null;
}

export function getNote(id) {
  return db.prepare("SELECT * FROM notes WHERE id = ?").get(id);
}

export function getNoteByPath(p) {
  return db.prepare("SELECT * FROM notes WHERE path = ?").get(p);
}

export function searchFts(query, limit = 20) {
  return db
    .prepare("SELECT n.id, n.title, n.type FROM notes_fts f JOIN notes n ON f.note_id = n.id WHERE notes_fts MATCH ? LIMIT ?")
    .all(query, limit);
}

export function listByType(type, limit = 50) {
  return db.prepare("SELECT id, title, type FROM notes WHERE type = ? LIMIT ?").all(type, limit);
}

export function listByTag(tag, limit = 50) {
  return db
    .prepare("SELECT n.id, n.title, n.type FROM tags t JOIN notes n ON t.note_id = n.id WHERE t.tag = ? LIMIT ?")
    .all(tag, limit);
}

export function listByProperty(key, value, limit = 50) {
  return db
    .prepare("SELECT n.id, n.title, n.type FROM properties p JOIN notes n ON p.note_id = n.id WHERE p.key = ? AND p.value = ? LIMIT ?")
    .all(key, value, limit);
}

// Numeric-range query over a property. Casts p.value to REAL inside SQLite so
// string-encoded numbers ("8.5", "9") compare correctly. Non-numeric values
// get NULL via CAST and are excluded by BETWEEN. Sorted DESC so the highest
// scores come back first.
export function listByPropertyRange(key, min, max, { type = null, limit = 50 } = {}) {
  const params = type ? [key, min, max, type, limit] : [key, min, max, limit];
  const typeClause = type ? " AND n.type = ?" : "";
  const sql = `SELECT n.id, n.title, n.type, p.value
    FROM properties p JOIN notes n ON p.note_id = n.id
    WHERE p.key = ? AND CAST(p.value AS REAL) BETWEEN ? AND ?${typeClause}
    ORDER BY CAST(p.value AS REAL) DESC
    LIMIT ?`;
  return db.prepare(sql).all(...params);
}

export function listByEntity(entity, limit = 50) {
  // "entity" queries are just alias lookups now — treat the entity name as a
  // link text and return everything that links to it.
  const targetId = resolveAlias(entity);
  if (!targetId) return [];
  return db
    .prepare("SELECT DISTINCT n.id, n.title, n.type FROM links l JOIN notes n ON l.source_id = n.id WHERE l.target_id = ? LIMIT ?")
    .all(targetId, limit);
}

export function backlinks(id, limit = 50) {
  return db
    .prepare("SELECT DISTINCT n.id, n.title, n.type FROM links l JOIN notes n ON l.source_id = n.id WHERE l.target_id = ? LIMIT ?")
    .all(id, limit);
}

export function listAll(limit = 100) {
  return db.prepare("SELECT id, title, type FROM notes ORDER BY updated DESC LIMIT ?").all(limit);
}

export function topByCentrality({ type = null, limit = 10 } = {}) {
  if (type) {
    return db
      .prepare("SELECT n.id, n.title, n.type, c.pagerank, c.degree_in, c.degree_out FROM centrality c JOIN notes n ON c.note_id = n.id WHERE n.type = ? ORDER BY c.pagerank DESC LIMIT ?")
      .all(type, limit);
  }
  return db
    .prepare("SELECT n.id, n.title, n.type, c.pagerank, c.degree_in, c.degree_out FROM centrality c JOIN notes n ON c.note_id = n.id ORDER BY c.pagerank DESC LIMIT ?")
    .all(limit);
}

export function danglingLinks(limit = 50) {
  return db
    .prepare("SELECT l.source_id, n.title AS source_title, l.target_text FROM links l JOIN notes n ON l.source_id = n.id WHERE l.target_id IS NULL LIMIT ?")
    .all(limit);
}

// Activate: seed from FTS matches on the query, run spreading activation,
// return the top-K notes with their titles. The retrieval primitive.
export function activate(query, { decay = 0.5, hops = 3, topK = 20 } = {}) {
  const seeds = {};
  const fts = db
    .prepare("SELECT note_id, bm25(notes_fts) AS score FROM notes_fts WHERE notes_fts MATCH ? ORDER BY score LIMIT 5")
    .all(query);
  // Lower bm25 score = better match; invert and normalize to [0,1]
  if (fts.length > 0) {
    const scores = fts.map((r) => r.score);
    const min = Math.min(...scores);
    const max = Math.max(...scores);
    const range = max - min || 1;
    for (const r of fts) {
      const normalized = 1 - (r.score - min) / range;
      seeds[r.note_id] = 0.5 + 0.5 * normalized;
    }
  }
  // Also seed from direct alias match (exact lookup gets maximum weight)
  const aliasHit = resolveAlias(query);
  if (aliasHit) seeds[aliasHit] = 1.0;

  if (Object.keys(seeds).length === 0) return [];

  const graph = new VaultGraph(db);
  const results = graph.spreadingActivation(seeds, { decay, hops, topK });
  // Enrich with titles + types
  const stmt = db.prepare("SELECT id, title, type FROM notes WHERE id = ?");
  return results.map((r) => {
    const note = stmt.get(r.id);
    return {
      id: r.id,
      title: note?.title || null,
      type: note?.type || null,
      weight: Number(r.weight.toFixed(4)),
    };
  });
}

export function neighbors(id, hops = 2) {
  const graph = new VaultGraph(db);
  const ids = [...graph.kHopNeighbors(id, hops)];
  const stmt = db.prepare("SELECT id, title, type FROM notes WHERE id = ?");
  return ids.map((n) => stmt.get(n)).filter(Boolean);
}

export function shortestPath(a, b) {
  const graph = new VaultGraph(db);
  const ids = graph.shortestPath(a, b);
  if (!ids) return null;
  const stmt = db.prepare("SELECT id, title, type FROM notes WHERE id = ?");
  return ids.map((n) => stmt.get(n)).filter(Boolean);
}

export default {
  init,
  resolveAlias,
  getNote,
  getNoteByPath,
  searchFts,
  listByType,
  listByTag,
  listByProperty,
  listByPropertyRange,
  listByEntity,
  backlinks,
  listAll,
  topByCentrality,
  danglingLinks,
  activate,
  neighbors,
  shortestPath,
  reindex: fullRebuild,
  close,
};
